CREATE TABLE user
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE file
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user INT,
    name VARCHAR(100) NOT NULL,
    path VARCHAR(255),
    FOREIGN KEY (user) REFERENCES user(id)

);

CREATE TABLE event
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user INT NOT NULL,
    file INT NOT NULL,
    date TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    occasion VARCHAR(50),
    FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (file) REFERENCES file(id)
);