CREATE TABLE IF NOT EXISTS user
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS file
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    path VARCHAR(255)

);

CREATE TABLE IF NOT EXISTS event
(
    id INT AUTO_INCREMENT PRIMARY KEY,
    user INT NOT NULL,
    file INT,
    date TIMESTAMP
        DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,
    occasion VARCHAR(50),
    FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE,
    FOREIGN KEY (file) REFERENCES file(id) ON DELETE SET NULL
);

COMMIT;